# Generated by Django 5.1.7 on 2025-06-03 16:37

import django.db.models.deletion
import home.models
import modelcluster.contrib.taggit
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sessions", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("grade", models.CharField(max_length=50)),
                ("enrollment_date", models.DateField()),
                ("conclusion_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="JobItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=50)),
                ("employment_date", models.DateField()),
                ("termination_date", models.DateField()),
                ("role", models.CharField(max_length=100)),
                ("role_description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReferralToken",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=home.models.default_token,
                        max_length=14,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("L0", "public"),
                            ("L1", "restricted social media"),
                            ("L2", "v-card"),
                            ("L3", "private"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                (
                    "expire_date",
                    models.DateField(
                        default=home.models.default_expire_date
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral Token",
            },
        ),
        migrations.CreateModel(
            name="SkillDescriptionItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, null=True)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "l0_e_mail",
                    models.CharField(
                        default="buisness+twd4@mariansyska.de",
                        max_length=100,
                        verbose_name="Public E-mail",
                    ),
                ),
                (
                    "l1_e_mail",
                    models.CharField(
                        default="buisness+sgtc@mariansyska.de",
                        max_length=100,
                        verbose_name="Semi-Private 1 E-mail",
                    ),
                ),
                (
                    "l2_e_mail",
                    models.CharField(
                        default="buisness+p7c4@mariansyska.de",
                        max_length=100,
                        verbose_name="Semi-Private 2 E-mail",
                    ),
                ),
                (
                    "l3_e_mail",
                    models.CharField(
                        default="buisness+ofd1@mariansyska.de",
                        max_length=100,
                        verbose_name="Private E-mail",
                    ),
                ),
                ("subtext", models.TextField()),
                ("linkedin_link", models.URLField()),
                ("github_link", models.URLField()),
                (
                    "portrait",
                    models.ForeignKey(
                        help_text="Project Image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_title", models.CharField(max_length=50)),
                (
                    "show_title",
                    models.BooleanField(
                        default=False, verbose_name="Show title on thumbnail"
                    ),
                ),
                ("description", models.TextField()),
                ("github_link", models.URLField(blank=True, null=True)),
                (
                    "image",
                    models.ForeignKey(
                        help_text="Project Image",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SkillSubDescriptionItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "skill_item",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_subdescription_items",
                        to="home.skilldescriptionitem",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SkillSubSubDescriptionItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "skill_item",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_subsubdescription_items",
                        to="home.skillsubdescriptionitem",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TechnologyTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="home.portfolioitem",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="taggit.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="home.TechnologyTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_viewed", models.DateField(null=True)),
                ("view_count", models.IntegerField(default=0)),
                (
                    "referral_token",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.referraltoken",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sessions.session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Request Log",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("referral_token", "session"),
                        name="referral_token_session_uniqueness",
                    )
                ],
            },
        ),
    ]
