# Generated by Django 5.1.7 on 2025-11-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="l0_e_mail",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="l1_e_mail",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="l2_e_mail",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="l3_e_mail",
        ),
        migrations.AddField(
            model_name="homepage",
            name="e_mail",
            field=models.CharField(default="marian.syska@gmail.com", max_length=100),
        ),
    ]
