# Generated by Django 5.1.7 on 2025-11-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_homepage_l0_e_mail_remove_homepage_l1_e_mail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="github_link",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="linkedin_link",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="subtext",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="jobitem",
            name="role_description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="github_link",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="referraltoken",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="skilldescriptionitem",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="skillsubdescriptionitem",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="skillsubsubdescriptionitem",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
