# Generated by Django 5.1.7 on 2025-11-14 14:54

import django.db.models.deletion
import home.models.pages.base_page
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_homepage_github_link_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BasePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("subtext", models.CharField(blank=True, default="", max_length=200)),
                ("menu_icon", models.CharField(blank=True, default="", max_length=200)),
                (
                    "avatar",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=home.models.pages.base_page.get_superuser,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.RemoveField(
            model_name="educationitem",
            name="enrollment_date",
        ),
        migrations.AlterField(
            model_name="educationitem",
            name="conclusion_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="educationitem",
            name="grade",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="jobitem",
            name="role_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="CVPage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.basepage",
                    ),
                ),
                ("linkedin_link", models.URLField(blank=True)),
                ("github_link", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "CV",
            },
            bases=("home.basepage",),
        ),
        migrations.CreateModel(
            name="PortfolioPage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.basepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio",
            },
            bases=("home.basepage",),
        ),
        migrations.DeleteModel(
            name="HomePage",
        ),
    ]
