# Generated by Django 5.1.7 on 2025-12-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("home", "0005_alter_skilldescriptionitem_sort_order"),
        ("home", "0006_alter_portfolioitem_options_portfolioitem_sort_order"),
    ]

    dependencies = [
        ("home", "0004_basepage_remove_educationitem_enrollment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skilldescriptionitem",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterModelOptions(
            name="portfolioitem",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
