# Generated by Django 5.1.7 on 2025-12-05 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "home",
            "0005_alter_skilldescriptionitem_sort_order_squashed_0006_alter_portfolioitem_options_portfolioitem_sort_order",
        ),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="portfolioitem",
            options={"ordering": ("sort_order",)},
        ),
        migrations.AlterModelOptions(
            name="skilldescriptionitem",
            options={"ordering": ("sort_order",)},
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="expire_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="expiry date/time"
            ),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="expired",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="expired"
            ),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="first_published_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="first published at"
            ),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="go_live_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="go live date/time"
            ),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="has_unpublished_changes",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="has unpublished changes"
            ),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="last_published_at",
            field=models.DateTimeField(
                editable=False, null=True, verbose_name="last published at"
            ),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="latest_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
                verbose_name="latest revision",
            ),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="live",
            field=models.BooleanField(
                default=True, editable=False, verbose_name="live"
            ),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="live_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
                verbose_name="live revision",
            ),
        ),
        migrations.AddField(
            model_name="skilldescriptionitem",
            name="expire_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="expiry date/time"
            ),
        ),
        migrations.AddField(
            model_name="skilldescriptionitem",
            name="expired",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="expired"
            ),
        ),
        migrations.AddField(
            model_name="skilldescriptionitem",
            name="first_published_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="first published at"
            ),
        ),
        migrations.AddField(
            model_name="skilldescriptionitem",
            name="go_live_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="go live date/time"
            ),
        ),
        migrations.AddField(
            model_name="skilldescriptionitem",
            name="has_unpublished_changes",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="has unpublished changes"
            ),
        ),
        migrations.AddField(
            model_name="skilldescriptionitem",
            name="last_published_at",
            field=models.DateTimeField(
                editable=False, null=True, verbose_name="last published at"
            ),
        ),
        migrations.AddField(
            model_name="skilldescriptionitem",
            name="latest_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
                verbose_name="latest revision",
            ),
        ),
        migrations.AddField(
            model_name="skilldescriptionitem",
            name="live",
            field=models.BooleanField(
                default=True, editable=False, verbose_name="live"
            ),
        ),
        migrations.AddField(
            model_name="skilldescriptionitem",
            name="live_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
                verbose_name="live revision",
            ),
        ),
    ]
