# Generated by Django 5.1.7 on 2025-12-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_siterootpage"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SiteRootPage",
        ),
        migrations.CreateModel(
            name="SiteRootPage",
            fields=[],
            options={
                "verbose_name": "Site Root",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("wagtailcore.page",),
        ),
    ]
