# Generated by Django 5.1.7 on 2026-05-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_siterootpage_siterootpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobitem',
            name='current_job',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobitem',
            name='show_dates',
            field=models.BooleanField(default=True),
        ),
    ]
