# Generated by Django 5.1.7 on 2026-07-20 17:02

import django.db.models.deletion
import home.models.referral
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_jobitem_current_job_jobitem_show_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='github_link',
        ),
        migrations.CreateModel(
            name='PortfolioItemLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon_class', models.CharField(choices=[('bi bi-github', 'Github'), ('bi bi-mortarboard-fill', 'Hochschule'), ('bi bi bi-globe', 'Globus')], default='bi bi-github', max_length=100)),
                ('text', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('portfolio_item', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='home.portfolioitem')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
