# Generated by Django 5.1.7 on 2026-07-21 10:40

from django.db import migrations


def modify_to_longtext(apps, schema_editor):
    if schema_editor.connection.vendor == 'mysql':
        schema_editor.execute(
            "ALTER TABLE home_jobitem"
            "MODIFY COLUMN role_description LONGTEXT;"
        )

def reverse_to_text(apps, schema_editor):
    if schema_editor.connection.vendor == 'mysql':
        schema_editor.execute(
            "ALTER TABLE home_jobitem"
            "MODIFY COLUMN role_description TEXT;"
        )

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_portfolioitem_github_link_and_more'),
    ]

    operations = [
        migrations.RunPython(modify_to_longtext, reverse_code=reverse_to_text),
    ]
