name: Deploy to Production
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            # Change to maintenance mode
            
            sudo ln -sfn /etc/nginx/sites-available/maintenance.conf /etc/nginx/sites-enabled/nginx.conf
            sudo systemctl reload nginx


            # Stop the application

            sudo systemctl stop portfolio-webapp


            # Update code

            cd /home/wagtail/portfolio-webapp
            git pull origin main


            # Activate virtual environment

            source venv/bin/activate


            # Install Python dependencies

            python3 -m pip install --upgrade pip
            pip install -r requirements.txt


            # Set up Django server

            python manage.py migrate --noinput
            python compile_scss.py
            python manage.py collectstatic --noinput


            # Start Django server

            sudo systemctl start portfolio-webapp


            # Change back to normal mode

            sudo ln -sfn /etc/nginx/sites-available/standard.conf /etc/nginx/sites-enabled/nginx.conf
            sudo systemctl reload nginx